import { Link } from "react-router-dom";
import { useLanguage } from "./i18n/LanguageContext.jsx";
import { GUIROPA_EMBLEM_SRC } from "./data/brandAssets.js";
import ScheduleLiveAgenda from "./components/ScheduleLiveAgenda.jsx";

const DECADE_ACTION={"1950s":"/ouvir?era=50s","1960s":"/ouvir?era=60s","1970s":"/70s","1980s":"/1986","1990":"/ouvir?era=90s"};
const COPY={
pt:{eyebrow:"GUIROPA RADIO · PROGRAMAÇÃO",title:"Programação",lead:"Cinco décadas. Cinco universos sonoros. Uma programação construída em torno da música que atravessou gerações.",sectionEyebrow:"NO AR",sectionTitle:"Uma década de cada vez.",sectionLead:"Escolha uma época. Agora cada década é uma porta de verdade para ouvir e explorar.",enter:"ENTRAR NA DÉCADA →",decades:[
{year:"1950s",title:"A FAÍSCA",description:"Rock 'n' roll, rhythm & blues, doo-wop e harmonias vocais.",shows:[["SEG · 18:00","The Birth of Rock"],["QUA · 20:00","Rhythm & Blues"],["SEX · 21:00","Rock 'n' Roll Classics"]]},
{year:"1960s",title:"TUDO MUDOU",description:"Pop, soul, Motown, folk rock e British Invasion.",shows:[["TER · 18:00","British Invasion"],["QUI · 20:00","Motown & Soul"],["SÁB · 19:00","Sixties Radio"]]},
{year:"1970s",title:"ANOS DOURADOS",description:"Soft rock, baladas, soul, disco e pop melódico.",shows:[["SEG · 20:00","Seventies Gold"],["QUA · 21:00","Soft Rock Nights"],["SÁB · 21:00","Disco & Soul"]]},
{year:"1980s",title:"HITS ETERNOS",description:"Power ballads, synthpop, arena rock e as grandes vozes da década.",shows:[["TER · 20:00","Eighties Forever"],["SEX · 20:00","Power Ballads"],["SÁB · 22:00","After Dark 80s"]]},
{year:"1990",title:"A ÚLTIMA PARADA",description:"Rock ballads, soft rock e canções eternas. A GUIROPA chega a 1990.",shows:[["QUA · 19:00","The Final Chapter"],["SEX · 22:00","1990"],["DOM · 20:00","GUIROPA Classics"]]}]},
en:{eyebrow:"GUIROPA RADIO · SCHEDULE",title:"Schedule",lead:"Five decades. Five musical worlds. Programming built around music that crossed generations.",sectionEyebrow:"ON AIR",sectionTitle:"One decade at a time.",sectionLead:"Choose an era. Every decade is now a real door to listen and explore.",enter:"ENTER THE DECADE →"},
es:{eyebrow:"GUIROPA RADIO · PROGRAMACIÓN",title:"Programación",lead:"Cinco décadas. Cinco universos sonoros. Una programación construida alrededor de la música que atravesó generaciones.",sectionEyebrow:"AL AIRE",sectionTitle:"Una década a la vez.",sectionLead:"Elige una época. Cada década ahora es una puerta real para escuchar y explorar.",enter:"ENTRAR EN LA DÉCADA →"}
};
export default function SchedulePage(){const{lang}=useLanguage();const base=COPY.pt;const c={...base,...(COPY[lang]||{})};return <main className="guiropa-schedule-page"><style>{`
.guiropa-schedule-page{--ink:#211c17;--soft:#665846;min-height:100vh;background:linear-gradient(180deg,#f7eddc,#f1dfc0 54%,#e9d2ae);color:var(--ink)}.guiropa-schedule-page *{box-sizing:border-box}.schedule-shell{width:min(1180px,calc(100% - 40px));margin:auto}.schedule-hero{padding:clamp(4rem,8vw,7rem) 0}.schedule-hero-grid{display:grid;grid-template-columns:1fr minmax(180px,260px);gap:4rem;align-items:end}.schedule-eye{color:#b83224;font-size:.7rem;font-weight:900;letter-spacing:.22em}.schedule-hero h1{font-size:clamp(4rem,9vw,8.5rem);line-height:.86;letter-spacing:-.065em;margin:.8rem 0}.schedule-hero p,.schedule-head p{color:var(--soft);line-height:1.7}.schedule-emblem img{width:100%;max-width:220px;border-radius:28px}.schedule-content{padding:4.5rem 0 6rem;border-top:1px solid rgba(77,57,39,.19)}.schedule-head h2{font-family:Georgia,serif;font-size:clamp(2.8rem,5vw,5rem);font-weight:400;line-height:.98;margin:.7rem 0}.schedule-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));margin-top:3rem;border:1px solid rgba(77,57,39,.19)}.schedule-card{padding:1.5rem;border-right:1px solid rgba(77,57,39,.19);text-decoration:none;color:inherit;transition:.25s;background:rgba(255,249,238,.3)}.schedule-card:last-child{border-right:0}.schedule-card:hover,.schedule-card:focus-visible{transform:translateY(-6px);background:#fff4df;box-shadow:0 18px 38px rgba(69,47,30,.13);outline:2px solid var(--accent);outline-offset:-2px}.schedule-card:nth-child(1){--accent:#c53a2d}.schedule-card:nth-child(2){--accent:#258b88}.schedule-card:nth-child(3){--accent:#df7a20}.schedule-card:nth-child(4){--accent:#ed2f76}.schedule-card:nth-child(5){--accent:#2864a0}.schedule-year{font-family:Georgia,serif;font-size:clamp(2rem,3vw,3.1rem);color:var(--accent)}.schedule-card h3{color:var(--accent);font-size:.72rem;letter-spacing:.12em;margin:1.5rem 0 .8rem}.schedule-card p{font-size:.82rem;line-height:1.6;color:#5e5143;min-height:6.5em}.schedule-show{padding:.8rem 0;border-top:1px solid rgba(77,57,39,.16)}.schedule-show span{display:block;color:var(--accent);font-size:.57rem;font-weight:900}.schedule-show strong{font-size:.82rem}.schedule-enter{display:block;margin-top:1.2rem;color:var(--accent);font-size:.62rem;font-weight:900;letter-spacing:.08em}@media(max-width:1000px){.schedule-grid{grid-template-columns:repeat(2,1fr)}.schedule-card{border-bottom:1px solid rgba(77,57,39,.19)}}@media(max-width:720px){.schedule-shell{width:min(100% - 24px,650px)}.schedule-hero-grid,.schedule-grid{grid-template-columns:1fr}.schedule-card{border-right:0}.schedule-card p{min-height:0}.schedule-emblem img{max-width:170px}}
`}</style><section className="schedule-hero"><div className="schedule-shell schedule-hero-grid"><div><span className="schedule-eye">{c.eyebrow}</span><h1>{c.title}</h1><p>{c.lead}</p></div><div className="schedule-emblem"><img src={GUIROPA_EMBLEM_SRC} alt="GUIROPA RADIO"/></div></div></section><section className="schedule-content"><div className="schedule-shell"><header className="schedule-head"><span className="schedule-eye">{c.sectionEyebrow}</span><h2>{c.sectionTitle}</h2><p>{c.sectionLead}</p></header><div className="schedule-grid">{base.decades.map(d=><Link className="schedule-card" to={DECADE_ACTION[d.year]} key={d.year}><span className="schedule-year">{d.year}</span><h3>{d.title}</h3><p>{d.description}</p>{d.shows.map(([time,title])=><div className="schedule-show" key={title}><span>{time}</span><strong>{title}</strong></div>)}<span className="schedule-enter">{c.enter}</span></Link>)}</div></div></section><ScheduleLiveAgenda/></main>}
