import { Link } from "react-router-dom";
import { useLanguage } from "../i18n/LanguageContext.jsx";

const COPY={
 pt:{tag:"APOIE A GUIROPA",title:"R$ 1 já ajuda a manter a GUIROPA no ar.",text:"Você ouve, lê e entra nos túneis. Se puder, ajude a manter tudo funcionando.",action:"APOIAR AGORA →"},
 en:{tag:"SUPPORT GUIROPA",title:"Even R$ 1 helps keep GUIROPA on air.",text:"You listen, read and enter the tunnels. If you can, help keep everything running.",action:"SUPPORT NOW →"},
 es:{tag:"APOYA GUIROPA",title:"Incluso R$ 1 ayuda a mantener GUIROPA al aire.",text:"Escuchas, lees y entras en los túneles. Si puedes, ayuda a mantener todo funcionando.",action:"APOYAR AHORA →"}
};
export default function GlobalSupportStrip(){const{lang}=useLanguage();const c=COPY[lang]||COPY.pt;return <section className="guiropa-global-support" aria-label={c.tag}><style>{`.guiropa-global-support{background:#17120e;color:#f5ead6;border-top:1px solid #332419}.guiropa-global-support__shell{width:min(1180px,calc(100% - 40px));margin:0 auto;padding:clamp(2.3rem,4vw,3.4rem) 0;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:28px;align-items:center}.guiropa-global-support__tag{color:#d9b467;font-size:.68rem;font-weight:900;letter-spacing:.18em}.guiropa-global-support h2{margin:.55rem 0 0;font-family:Georgia,"Times New Roman",serif;font-size:clamp(2rem,4vw,3.6rem);font-weight:400;line-height:.96;letter-spacing:-.045em}.guiropa-global-support p{margin:.8rem 0 0;color:#b5a38d;line-height:1.6}.guiropa-global-support a{display:inline-flex;min-height:48px;align-items:center;padding:0 18px;background:#b83224;color:#fff5e7;text-decoration:none;font-size:.68rem;font-weight:900;letter-spacing:.1em;white-space:nowrap}@media(max-width:720px){.guiropa-global-support__shell{width:min(100% - 24px,650px);grid-template-columns:1fr}.guiropa-global-support a{justify-self:start}}`}</style><div className="guiropa-global-support__shell"><div><span className="guiropa-global-support__tag">{c.tag}</span><h2>{c.title}</h2><p>{c.text}</p></div><Link to="/apoie">{c.action}</Link></div></section>}
